version: '3.2'

services:
  mongo:
    container_name: mongo_local_db
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    
  postgres:
    container_name: postgres_local_db
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbit_mq:
    container_name: rabbit_mq_local
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
      - 5672:5672