version: '3'

services:

  rabbit_mq:
    container_name: rabbit_mq
    image: rabbitmq:3.12-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  api_gateway:
    image: devopsfaith/krakend
    container_name: api_gateway
    volumes:
      - ./gateway:/etc/krakend/
    ports:
      - 80:8080
    extra_hosts:
    - "host.docker.internal:host-gateway"

  users:
    container_name: users_ms
    restart: on-failure
    build:
      context: ./
      dockerfile: ./users/Dockerfile
    depends_on:
      - rabbit_mq
    links:
      - mongo
      - rabbit_mq
      
  posts:
    container_name: posts_ms
    restart: on-failure
    build:
      context: ./
      dockerfile: ./posts/Dockerfile
    depends_on:
      - rabbit_mq
    links:
     - postgres
     - rabbit_mq

  auth:
    container_name: auth_ms
    build:
      context: ./
      dockerfile: ./auth/Dockerfile
  
  mongo:
    container_name: mongo_ms
    image: mongo
    
  postgres:
    container_name: postgres_ms
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example